from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Generic, TypeVar

from loom.core.errors.errors import LoomError

ResultT = TypeVar("ResultT")


class JobTimeoutError(LoomError):
    """Raised when waiting for a job result exceeds the requested timeout.

    Args:
        job_id: UUID of the timed-out job.
        timeout: The timeout value that was exceeded, in seconds.

    Example::

        raise JobTimeoutError("abc-123", timeout=30.0)
    """

    def __init__(self, job_id: str, timeout: float | None = None) -> None:
        msg = f"Job {job_id!r} timed out"
        if timeout is not None:
            msg += f" after {timeout}s"
        super().__init__(msg, code="job_timeout")
        self.job_id = job_id
        self.timeout = timeout


class JobFailedError(LoomError):
    """Raised when a job fails during execution.

    Wraps the underlying cause so callers can inspect it without catching
    arbitrary exceptions directly.

    Args:
        job_id: UUID of the failed job.
        cause: The exception that caused the failure, if available.

    Example::

        raise JobFailedError("abc-123", cause=exc)
    """

    def __init__(self, job_id: str, cause: BaseException | None = None) -> None:
        msg = f"Job {job_id!r} failed"
        if cause is not None:
            msg += f": {cause}"
        super().__init__(msg, code="job_failed")
        self.job_id = job_id
        self.cause = cause


@dataclass(frozen=True)
class JobHandle(Generic[ResultT]):
    """Represents a dispatched job and allows waiting for its result.

    Created by ``JobService.dispatch()`` immediately — before the job is
    actually sent to the broker.  The ``job_id`` is a UUID generated by the
    framework and passed to Celery as ``task_id`` so both sides share the
    same identifier.

    Two execution modes are supported transparently:

    - **Celery mode**: ``_async_result`` is a Celery ``AsyncResult``.
      ``wait()`` delegates to ``AsyncResult.get(timeout=timeout)``.
    - **Inline mode** (tests / ``InlineJobService``): ``_async_result`` is
      ``None``.  The runner appends the result to ``_inline_result_holder``
      after execution; ``wait()`` returns ``_inline_result_holder[0]``.

    Attributes:
        job_id: UUID pre-generated by the framework and shared with Celery.
        queue: The Celery queue the job was dispatched to.
        dispatched_at: UTC timestamp of when the handle was created.

    Args:
        job_id: UUID string.
        queue: Target queue name.
        dispatched_at: UTC timestamp.
        _async_result: Celery ``AsyncResult`` or ``None`` for inline mode.
        _inline_result_holder: Mutable list populated by the inline runner;
            ignored in Celery mode.

    Example::

        handle = service.dispatch(SendEmailJob, payload={"user_id": 1})
        result = handle.wait(timeout=10.0)
    """

    job_id: str
    queue: str
    dispatched_at: datetime
    _async_result: Any = field(default=None, repr=False, compare=False)
    _inline_result_holder: list[Any] = field(default_factory=list, repr=False, compare=False)

    def wait(self, timeout: float | None = None) -> ResultT:
        """Block until the job completes and return its result.

        In Celery mode, delegates to ``AsyncResult.get()``.  In inline mode,
        returns the result already stored by the runner.

        Args:
            timeout: Maximum seconds to wait.  ``None`` waits indefinitely.

        Returns:
            The value returned by ``Job.execute()``.

        Raises:
            JobTimeoutError: If the timeout is exceeded.
            JobFailedError: If the job raised an exception.
        """
        if self._async_result is None:
            return self._inline_result_holder[0]  # type: ignore[no-any-return]
        return self._wait_async(timeout)

    def _wait_async(self, timeout: float | None) -> ResultT:
        try:
            return self._async_result.get(timeout=timeout)  # type: ignore[no-any-return]
        except Exception as exc:
            if type(exc).__name__ == "TimeoutError":
                raise JobTimeoutError(self.job_id, timeout) from exc
            raise JobFailedError(self.job_id, exc) from exc


@dataclass(frozen=True)
class JobGroup:
    """Represents a group of concurrently dispatched jobs.

    Created by ``JobService.dispatch_parallel()``.  Provides a
    ``wait_all()`` to collect all results and a ``then()`` stub for
    Celery chord support.

    Attributes:
        handles: Ordered tuple of handles, one per dispatched job.

    Example::

        group = service.dispatch_parallel([
            (SendEmailJob, {"user_id": 1}),
            (SendEmailJob, {"user_id": 2}),
        ])
        results = group.wait_all(timeout=30.0)
    """

    handles: tuple[JobHandle[Any], ...]

    def wait_all(self, timeout: float | None = None) -> list[Any]:
        """Wait for every handle and return results in dispatch order.

        Args:
            timeout: Per-handle timeout in seconds.  ``None`` waits
                indefinitely for each handle.

        Returns:
            List of results aligned with ``handles`` order.

        Raises:
            JobTimeoutError: If any handle exceeds ``timeout``.
            JobFailedError: If any job failed.
        """
        return [handle.wait(timeout) for handle in self.handles]

    def then(
        self,
        job_type: type[Any],
        payload: dict[str, Any] | None = None,
        on_success: type[Any] | None = None,
        on_failure: type[Any] | None = None,
    ) -> JobGroup:
        """Schedule a job to run after all handles complete (chord).

        Stub in the core layer.  The real implementation is provided by
        ``CeleryJobService``, which returns a chord-capable ``JobGroup``
        subclass from ``dispatch_parallel()``.

        Raises:
            NotImplementedError: Always — use ``CeleryJobService`` for
                chord support.
        """
        raise NotImplementedError(
            "JobGroup.then() requires a Celery-backed service. "
            "Use CeleryJobService.dispatch_parallel() to obtain chord support."
        )
