"""Reusable streaming flow-case builders and shared test models."""

from __future__ import annotations

from tests.unit.streaming.flows.cases.batch import (
    build_async_flow_case,
    build_with_batch_flow_case,
    build_with_batch_scope_flow_case,
)
from tests.unit.streaming.flows.cases.fork import (
    build_fork_flow_case,
    build_fork_when_flow_case,
    build_fork_with_flow_case,
)
from tests.unit.streaming.flows.cases.router import build_router_flow_case
from tests.unit.streaming.flows.cases.shared import (
    _ORDERS_FORK_STANDARD_TOPIC,
    _ORDERS_FORK_VIP_TOPIC,
    _ORDERS_PRICED_BATCH_SCOPE_TOPIC,
    _ORDERS_PRICED_TOPIC,
    _ORDERS_RAW_TOPIC,
    _ORDERS_ROUTED_TOPIC,
    _ORDERS_SCORED_TOPIC,
    _ORDERS_VALIDATED_TOPIC,
    FakePricingClient,
    FakeRiskClient,
    MarkManualOrder,
    MarkStandardOrder,
    MarkVipOrder,
    OrderPlaced,
    PricedOrder,
    PriceOrder,
    ResourceEvents,
    RiskScoredOrder,
    RoutedOrder,
    ScoreRiskAsync,
    StreamFlowCase,
    ValidatedOrder,
    ValidateOrder,
    _build_case,
    _message,
    _routed_order_message,
)
from tests.unit.streaming.flows.cases.simple import build_simple_validation_flow_case

__all__ = [
    "FakePricingClient",
    "FakeRiskClient",
    "MarkManualOrder",
    "MarkStandardOrder",
    "MarkVipOrder",
    "OrderPlaced",
    "PricedOrder",
    "PriceOrder",
    "ResourceEvents",
    "RiskScoredOrder",
    "RoutedOrder",
    "ScoreRiskAsync",
    "StreamFlowCase",
    "ValidateOrder",
    "ValidatedOrder",
    "_ORDERS_FORK_STANDARD_TOPIC",
    "_ORDERS_FORK_VIP_TOPIC",
    "_ORDERS_PRICED_BATCH_SCOPE_TOPIC",
    "_ORDERS_PRICED_TOPIC",
    "_ORDERS_RAW_TOPIC",
    "_ORDERS_ROUTED_TOPIC",
    "_ORDERS_SCORED_TOPIC",
    "_ORDERS_VALIDATED_TOPIC",
    "_build_case",
    "_message",
    "_routed_order_message",
    "build_async_flow_case",
    "build_fork_flow_case",
    "build_fork_when_flow_case",
    "build_fork_with_flow_case",
    "build_router_flow_case",
    "build_simple_validation_flow_case",
    "build_with_batch_flow_case",
    "build_with_batch_scope_flow_case",
]
