"""ETL run observer protocol and built-in implementations.

The observer is the observability contract of the executor.  Every lifecycle
event — pipeline start/end, process start/end, step start/end, step error —
is routed through it.

A :class:`CompositeRunObserver` fans out to N observers simultaneously,
so you are never forced to choose between destinations::

    observer = CompositeRunObserver(
        LoggingRunObserver(),          # stdout via stdlib logging
        DeltaRunObserver(writer),      # write runs/ to Delta Lake
        OTelRunObserver(endpoint=...), # emit to any OTLP collector
    )

Event model
-----------
Each pipeline/process/step run gets a unique ``run_id`` / ``*_run_id`` UUID
generated by the executor.  These map directly to OpenTelemetry Trace / Span
identifiers, making future OTel integration a thin adapter.
"""

from __future__ import annotations

import logging
from enum import StrEnum
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    from loom.etl.compiler._plan import PipelinePlan, ProcessPlan, StepPlan

_log = logging.getLogger("loom.etl")


class RunStatus(StrEnum):
    """Terminal status of a pipeline, process, or step run."""

    SUCCESS = "success"
    FAILED = "failed"


class EventName(StrEnum):
    """All lifecycle event names emitted by the executor.

    Use these constants instead of raw strings when filtering or asserting
    on observer events (e.g. in :class:`~loom.etl.testing.StubRunObserver`).
    """

    PIPELINE_START = "pipeline_start"
    PIPELINE_END = "pipeline_end"
    PROCESS_START = "process_start"
    PROCESS_END = "process_end"
    STEP_START = "step_start"
    STEP_END = "step_end"
    STEP_ERROR = "step_error"


@runtime_checkable
class ETLRunObserver(Protocol):
    """Protocol for ETL lifecycle observability.

    Implementations receive structured events at each phase of execution.
    All ``*_run_id`` values are UUID strings generated by the executor and
    correlate start/end pairs for the same unit of work.

    Implement this protocol to route events to any backend:
    structured logs, Delta tables, OpenTelemetry collectors, etc.

    Example::

        class MyObserver:
            def on_step_end(
                self,
                step_run_id: str,
                status: RunStatus,
                rows_read: int,
                rows_written: int,
                duration_ms: int,
            ) -> None:
                print(f"step={step_run_id} {status} {duration_ms}ms")
    """

    def on_pipeline_start(self, plan: PipelinePlan, params: Any, run_id: str) -> None:
        """Called before the first process of the pipeline executes."""
        ...

    def on_pipeline_end(self, run_id: str, status: RunStatus, duration_ms: int) -> None:
        """Called after all processes complete or on first unhandled error."""
        ...

    def on_process_start(self, plan: ProcessPlan, run_id: str, process_run_id: str) -> None:
        """Called before the first step of a process executes."""
        ...

    def on_process_end(self, process_run_id: str, status: RunStatus, duration_ms: int) -> None:
        """Called after all steps of the process complete or on error."""
        ...

    def on_step_start(self, plan: StepPlan, run_id: str, step_run_id: str) -> None:
        """Called before sources are read."""
        ...

    def on_step_end(
        self,
        step_run_id: str,
        status: RunStatus,
        rows_read: int,
        rows_written: int,
        duration_ms: int,
    ) -> None:
        """Called after the target write completes or on error.

        Args:
            step_run_id:  Unique ID for this step execution.
            status:       ``SUCCESS`` or ``FAILED``.
            rows_read:    Total source rows read across all sources.
                          ``0`` when the backend does not materialise before
                          writing (e.g. Polars LazyFrame).
            rows_written: Rows written to the target.  ``0`` when unknown.
            duration_ms:  Wall-clock time for the full step (read+exec+write).
        """
        ...

    def on_step_error(self, step_run_id: str, exc: Exception) -> None:
        """Called with the unhandled exception before ``on_step_end(FAILED)``."""
        ...


# ---------------------------------------------------------------------------
# Built-in implementations
# ---------------------------------------------------------------------------


class NoopRunObserver:
    """Observer that discards all events.  Default when no observer is injected."""

    def on_pipeline_start(self, plan: Any, params: Any, run_id: str) -> None:
        pass

    def on_pipeline_end(self, run_id: str, status: RunStatus, duration_ms: int) -> None:
        pass

    def on_process_start(self, plan: Any, run_id: str, process_run_id: str) -> None:
        pass

    def on_process_end(self, process_run_id: str, status: RunStatus, duration_ms: int) -> None:
        pass

    def on_step_start(self, plan: Any, run_id: str, step_run_id: str) -> None:
        pass

    def on_step_end(
        self,
        step_run_id: str,
        status: RunStatus,
        rows_read: int,
        rows_written: int,
        duration_ms: int,
    ) -> None:
        pass

    def on_step_error(self, step_run_id: str, exc: Exception) -> None:
        pass


class LoggingRunObserver:
    """Observer that emits structured key=value log lines via stdlib ``logging``.

    All events go to the ``loom.etl`` logger at INFO level (errors at ERROR).
    Wire a JSON formatter in production to make these machine-parseable.

    Args:
        logger: Override the default ``loom.etl`` logger if needed.

    Example::

        import logging
        logging.basicConfig(level=logging.INFO)
        executor = ETLExecutor(reader, writer, observer=LoggingRunObserver())
    """

    def __init__(self, logger: logging.Logger | None = None) -> None:
        self._log = logger or _log

    def on_pipeline_start(self, plan: Any, params: Any, run_id: str) -> None:
        self._log.info(
            "pipeline_start pipeline=%s run_id=%s",
            plan.pipeline_type.__name__,
            run_id,
        )

    def on_pipeline_end(self, run_id: str, status: RunStatus, duration_ms: int) -> None:
        self._log.info(
            "pipeline_end run_id=%s status=%s duration_ms=%d",
            run_id,
            status,
            duration_ms,
        )

    def on_process_start(self, plan: Any, run_id: str, process_run_id: str) -> None:
        self._log.info(
            "process_start process=%s run_id=%s process_run_id=%s",
            plan.process_type.__name__,
            run_id,
            process_run_id,
        )

    def on_process_end(self, process_run_id: str, status: RunStatus, duration_ms: int) -> None:
        self._log.info(
            "process_end process_run_id=%s status=%s duration_ms=%d",
            process_run_id,
            status,
            duration_ms,
        )

    def on_step_start(self, plan: Any, run_id: str, step_run_id: str) -> None:
        self._log.info(
            "step_start step=%s run_id=%s step_run_id=%s",
            plan.step_type.__name__,
            run_id,
            step_run_id,
        )

    def on_step_end(
        self,
        step_run_id: str,
        status: RunStatus,
        rows_read: int,
        rows_written: int,
        duration_ms: int,
    ) -> None:
        self._log.info(
            "step_end step_run_id=%s status=%s rows_read=%d rows_written=%d duration_ms=%d",
            step_run_id,
            status,
            rows_read,
            rows_written,
            duration_ms,
        )

    def on_step_error(self, step_run_id: str, exc: Exception) -> None:
        self._log.error(
            "step_error step_run_id=%s error=%r",
            step_run_id,
            exc,
        )


class CompositeRunObserver:
    """Fan-out observer that forwards every event to N observers simultaneously.

    Use this to combine destinations without choosing between them::

        observer = CompositeRunObserver(
            LoggingRunObserver(),
            DeltaRunObserver(writer),
            OTelRunObserver(endpoint="https://otel.company.com"),
        )

    Args:
        *observers: One or more :class:`ETLRunObserver` implementations.
    """

    def __init__(self, *observers: ETLRunObserver) -> None:
        self._observers = observers

    def on_pipeline_start(self, plan: Any, params: Any, run_id: str) -> None:
        for obs in self._observers:
            obs.on_pipeline_start(plan, params, run_id)

    def on_pipeline_end(self, run_id: str, status: RunStatus, duration_ms: int) -> None:
        for obs in self._observers:
            obs.on_pipeline_end(run_id, status, duration_ms)

    def on_process_start(self, plan: Any, run_id: str, process_run_id: str) -> None:
        for obs in self._observers:
            obs.on_process_start(plan, run_id, process_run_id)

    def on_process_end(self, process_run_id: str, status: RunStatus, duration_ms: int) -> None:
        for obs in self._observers:
            obs.on_process_end(process_run_id, status, duration_ms)

    def on_step_start(self, plan: Any, run_id: str, step_run_id: str) -> None:
        for obs in self._observers:
            obs.on_step_start(plan, run_id, step_run_id)

    def on_step_end(
        self,
        step_run_id: str,
        status: RunStatus,
        rows_read: int,
        rows_written: int,
        duration_ms: int,
    ) -> None:
        for obs in self._observers:
            obs.on_step_end(step_run_id, status, rows_read, rows_written, duration_ms)

    def on_step_error(self, step_run_id: str, exc: Exception) -> None:
        for obs in self._observers:
            obs.on_step_error(step_run_id, exc)
